# Generated by Django 3.2.5 on 2021-08-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210828_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=models.IntegerField(null=True, verbose_name='customer.Account Balance'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='one_time_pickup',
            field=models.DateField(null=True, verbose_name='customer.One Time Pickup'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_address',
            field=models.CharField(max_length=50, verbose_name='customer.Street Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspend_end',
            field=models.DateField(null=True, verbose_name='customer.Suspend End'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspend_start',
            field=models.DateField(null=True, verbose_name='customer.Suspend Start'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weekly_pickup_day',
            field=models.CharField(max_length=9, verbose_name='customer.Weekly Pickup Day'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=5, verbose_name='customer.Zip Code'),
        ),
    ]
