# Generated by Django 3.2.5 on 2021-08-29 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210828_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weekly_pickup_day',
        ),
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='customer.Balance'),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekly_pickup',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='one_time_pickup',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspend_end',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suspend_start',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
